dist: xenial
language: node_js
node_js:
  - 10
cache:
  directories:
    - $HOME/.npm
    - node_modules
install:
  - npm install
script:
  - npm test
after_success:
- codecov coverage/lcov.info -t ${CODECOV_TOKEN}
- echo 'Done!'
